### ISSUE TITLE
a error

### ISSUE THREAD

**Issue by calvindiao** [myetyet/jstc-uploader#1]
hello, thanks for your script.
However, I have a problem with uploading my photo. Here are some information.
```
Traceback (most recent call last):
  File "jstc.py", line 81, in <module>
    main(*sys.argv[1:])
  File "jstc.py", line 76, in main
    login(name, stuid, id)
  File "jstc.py", line 34, in login
    sess.headers["token"] = re.search(r"'/pages/selector/selector\?token=' \+ '(.+?)'", token_html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
My environment is macos. And my python version is 3.8.

**Comment by myetyet** [comment]
The code was written last year but uploaded recently. It was said that the miniprogram had been updated this year, and I had no test cases. I'll comment later after checking the DOM tree.

**Comment by myetyet** [comment]
No test cases, please provide a minimum demo.
